### ISSUE TITLE
TalReader doesn't read pairs.json files with version numbers

### ISSUE THREAD

**Issue by leondavis1** [pennmem/ptsa_new#116]
Traceback (most recent call last):
  File "RAM_FRcatFR1_calcPower_rhino_allchans_newPTSA.py", line 272, in <module>
    proc_sess(exp, period, ev[subjfilt & sessfilt])
  File "RAM_FRcatFR1_calcPower_rhino_allchans_newPTSA.py", line 137,
in proc_sess
    channels = tal_reader.get_monopolar_channels()
  File "/home1/cweidema/anaconda2/lib/python2.7/site-packages/ptsa/data/readers/TalReader.py",
line 59, in get_monopolar_channels
    bipolar_array = self.get_bipolar_pairs()
  File "/home1/cweidema/anaconda2/lib/python2.7/site-packages/ptsa/data/readers/TalReader.py",
line 48, in get_bipolar_pairs
    self.read()
  File "/home1/cweidema/anaconda2/lib/python2.7/site-packages/ptsa/data/readers/TalReader.py",
line 114, in read
    self.tal_struct_array = self.from_dict(pairs)
  File "/home1/cweidema/anaconda2/lib/python2.7/site-packages/ptsa/data/readers/TalReader.py",
line 77, in from_dict
    pairs = pd.DataFrame.from_dict(list(pairs.values())[0]['pairs'],
orient='index').sort_values(by=['channel_1','channel_2'])
TypeError: string indices must be integers

**Comment by leondavis1** [comment]
Addressed in #126
