### ISSUE TITLE
TimeSeries.to_hdf doesn't consistently work with events

### ISSUE THREAD

**Issue by leondavis1** [pennmem/ptsa_new#234]
Example: R1293P, catFR1, session 1

**Comment by leondavis1** [comment]
Specifically: `io.hdf5.save*` methods don't work on arrays with size-0 dtypes.

For example:
```python
>>> arr = np.array([b'',b''], dtype=[("empty","S")])
>>> arr['empty'].dtype.itemsize
0
>>> h5 = h5py.File('test.h5','w')
>>> save_records(h5,'test',arr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home1/leond/miniconda3/envs/ramutils-dev/lib/python3.6/site-packages/ptsa/io/hdf5.py", line 121, in save_records
    hfile[where] = sanitized
  File "/home1/leond/miniconda3/envs/ramutils-dev/lib/python3.6/site-packages/h5py/_hl/group.py", line 301, in __setitem__
    ds = self.create_dataset(None, data=obj, dtype=base.guess_dtype(obj))
  File "/home1/leond/miniconda3/envs/ramutils-dev/lib/python3.6/site-packages/h5py/_hl/group.py", line 116, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home1/leond/miniconda3/envs/ramutils-dev/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1611, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1655, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1568, in h5py.h5t._c_compound
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1666, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1487, in h5py.h5t._c_string
ValueError: Size must be positive (size must be positive)
```
