### ISSUE TITLE
ImportError: cannot import name MorletWaveletTransformMP

### ISSUE THREAD

**Issue by mivade** [pennmem/ptsa_new#54]
I get the above message on Windows using both versions 1.1.0 and 1.1.1 of the official conda package.

**Comment by mivade** [comment]
```
Traceback (most recent call last):
  File "C:\Users\OdinUser\src\SYS3\rampy\plugins\__init__.py", line 137, in queryPlugin
    module = imp.load_source(name, fname)
  File "C:\Users\OdinUser\src\SYS3\rampy\plugins\PS4\BiomarkerMonitor.py", line 25, in <module>
    from BiomarkerMonitorKernel import BiomarkerMonitorKernel
  File "C:\Users\OdinUser\src\SYS3\rampy\plugins\PS4\BiomarkerMonitorKernel.py", line 6, in <module>
    from ptsa.extensions import MorletWaveletTransformMP
ImportError: cannot import name MorletWaveletTransformMP
```

**Comment by mivade** [comment]
Workaround:

1. Clean entire PTSA directory: `git clean -fxd`
2. Re-install with `setup.py install`
3. Change import to read `from ptsa.extensions.morlet import MorletWaveletTransformMP`
