### ISSUE TITLE
'basestring' not defined when using JSONIndexReader

### ISSUE THREAD

**Issue by smeisler** [pennmem/ptsa_new#57]
I am attempting to create the JSON reader with the code:
jr = JsonIndexReader(rhino_root + '/protocols/r1.json')

and I get the following error:

```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/Users/smeisler/Documents/EEG_GUI_D1.py", line 38, in <module>
    jr = JsonIndexReader('/Volumes/RHINO2/protocols/r1.json')  # Build JSON reader
  File "/Users/smeisler/anaconda/lib/python3.6/site-packages/ptsa/data/readers/IndexReader.py", line 28, in __init__
    self._prepend_db_root(self.protocols_root, self.index)
  File "/Users/smeisler/anaconda/lib/python3.6/site-packages/ptsa/data/readers/IndexReader.py", line 39, in _prepend_db_root
    cls._prepend_db_root(protocols_root, v)
  File "/Users/smeisler/anaconda/lib/python3.6/site-packages/ptsa/data/readers/IndexReader.py", line 39, in _prepend_db_root
    cls._prepend_db_root(protocols_root, v)
  File "/Users/smeisler/anaconda/lib/python3.6/site-packages/ptsa/data/readers/IndexReader.py", line 39, in _prepend_db_root
    cls._prepend_db_root(protocols_root, v)
  [Previous line repeated 4 more times]
  File "/Users/smeisler/anaconda/lib/python3.6/site-packages/ptsa/data/readers/IndexReader.py", line 40, in _prepend_db_root
    elif isinstance(v, basestring):
NameError: name 'basestring' is not defined
```

I looked through IndexReader.py and I could not find how basestring is defined.

**Comment by smeisler** [comment]
Apparently 'basestring' and 'unicode', both prominently featured in the PTSA reader functions, are not compatible with python 3.

**Comment by mivade** [comment]
A workaround is to update all instances of `basestring` to use `ptsa.six.string_type` and `unicode` to use `ptsa.six.text_type` ([upstream documentation](https://pythonhosted.org/six/#constants)). I'll make these changes for the next release.
