### ISSUE TITLE
conda packages are broken

### ISSUE THREAD

**Issue by mivade** [pennmem/ptsa_new#77]
Example:

```python
>>> from ptsa.extensions.morlet import MorletWaveletTransformMP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\odinuser\miniconda3\envs\ram\lib\site-packages\ptsa\extensions\morlet\__init__.py", line 1, in <module>
    from .morlet import *
  File "c:\users\odinuser\miniconda3\envs\ram\lib\site-packages\ptsa\extensions\morlet\morlet.py", line 101, in <module>
    POWER = _morlet.POWER
AttributeError: 'module' object has no attribute 'POWER'
'module' object has no attribute 'POWER'
```

**Comment by mivade** [comment]
This seems to apply to (some?) of the Linux packages, too: `ram_utils` tests are failing for the same reason. This is a high priority since we have so much that relies on PTSA and having to first build everything adds quite a bit of time to testing.

**Comment by mivade** [comment]
Rebuilt the Python 2.7 package (which is all `ram_utils` is testing on right now) and it seems to work on linux-64. Still not clear on what the issue is...
